---
- name: Copy the Redis Exporter systemd service file
  ansible.builtin.template:
    src: redis-exporter.service.j2
    dest: /etc/systemd/system/redis-exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart redis-exporter
